version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: prueba
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php-apache:
    build: .
    container_name: mi_php_apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mi_mysql
      - MYSQL_DATABASE=prueba
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=password123
