DROP DATABASE IF EXISTS `test21`;
CREATE DATABASE IF NOT EXISTS `test21`;
USE `test21`;

CREATE TABLE IF NOT EXISTS listado_clientes (
  id INT AUTO_INCREMENT, 
  email VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  telephone VARCHAR(15) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
